### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by ForsakenNGS** [Renaud11232/OctoPrint-Marlin-Flasher#36]
TLDR: Do you accept donations / where can I tip you?

Long story: I'm rebuilding my first self-built 3d printer into a ultra-low-duty CNC, which requires a lot of firmware tweaking right now. Not having to replug the board all the time is really a godsend. For the amount of time you save me I'd love to give you a small tip and probably others feel the same way, too.

**Comment by Renaud11232** [comment]
Hello,
I'm really glad you like the plugin :)
This is why I created it, I wanted a way to upgrade the firmware without the need of plugging it to another computer.

That being said, I currently don't have anything setup for donations/tips simply because I didn't even think about it.

I will try to set this up. Without any obligation of course.

**Comment by Renaud11232** [comment]
Hello,
I've added a [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UD54SHVYDV6NU&source=url) button in the readme.
I just have to thank you then, if you still want to donate, of course, this is not an obligation

**Comment by ForsakenNGS** [comment]
It took me a while, but better late then never. Have a drink on me :)
