### ISSUE TITLE
Please add option to copy/flash PlatformIO .bin file 

### ISSUE THREAD

**Issue by AndKe** [Renaud11232/OctoPrint-Marlin-Flasher#65]
OctoPi is very useful.
It is also an impressively wrong thing to use to compile a "platformio" project.
After configuring/testing on a workstation, the project. when zipped, easily becomes 55MB 
Ok, so I upload the file, wait too long while it unpacks on RPi3, then wait ridiculously long for the compilation of what I compiled in 5 seconds on the workstation.
This process is an utter waste of time, I can copy the .bin walk 100m to the printer and insert the SD faster than that.

Please make Marlin Flasher equally useful for PlatformIO projects, as it is with Arduino: accept .bin file as you accept .hex

**Comment by Renaud11232** [comment]
There is no way of directly using a bin file the same way arduino-cli does. I don't believe PlatformIO provides a way to do this.
Zipping the whole compiled project is not needed since, as you pointed out, it will be recompiled by PlatformIO.

Yes, I know it's a slow process, especially on RPi's.

If you believe this process is
* an impressively wrong thing to do
* an utter waste of time
* takes way too long
* is ridiculously long

Feel free to stop using the plugin and uninstall it.
Implying this plugin is pretty much useless in its current state won't make me want to help you.

In the meantime, I'll look if adding support for PlatformIO remote upload is possible (#71).
