### ISSUE TITLE
[FR] Apply precompiled firmware.

### ISSUE THREAD

**Issue by spacecabbie** [Renaud11232/OctoPrint-Marlin-Flasher#82]
**Is your feature request related to a problem? Please describe.**

I had thought this would allow me to upload firmware.bin to my surprise there is no option for this.
It actualy compiles every thing witch is nice but it would be handy to skip that and straight upload the bin file.

**Comment by Renaud11232** [comment]
Hello,

This has already been asked (#58).

Sadly, I don't believe there is a way to do that using PlatformIO.
The closest way to upload firmware without having to compile on the OctoPrint machine, would be to use Platform IO remote upload (#71). I have been working on adding this but at the moment there is an issue with PlatformIO and I don't have a way to fix it myself.

If you are using arduino-cli, you can already upload precompiled .hex files.

Depending on your board, the "Firmware Updater" plugin might be able to solve your issue. [Here are the supported board types](https://github.com/OctoPrint/OctoPrint-FirmwareUpdater#supported-boards).

I'm closing this since it's a duplicate
